#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
set -x
rsync -r --delete --exclude ".*" ${OPENSHIFT_REPO_DIR}/diy/tomee/conf/ ${OPENSHIFT_DATA_DIR}/tomee/conf/
rsync -r --delete --exclude ".*" ${OPENSHIFT_REPO_DIR}/diy/tomee/lib/ ${OPENSHIFT_DATA_DIR}/tomee/lib/
rsync -r --delete --exclude ".*" ${OPENSHIFT_REPO_DIR}/diy/tomee/webapps/ ${OPENSHIFT_DATA_DIR}/tomee/webapps/
rsync -r --delete --exclude ".*" ${OPENSHIFT_REPO_DIR}/diy/tomee/apps/ ${OPENSHIFT_DATA_DIR}/tomee/apps/
cd $OPENSHIFT_DATA_DIR/tomee
sed -ig 's/OPENSHIFT_DIY_IP/'$OPENSHIFT_DIY_IP'/g' conf/server.xml
sed -ig 's/OPENSHIFT_APP_DNS/'$OPENSHIFT_APP_DNS'/' conf/server.xml
bin/startup.sh